name: deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Flutter build and deploy
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: Say start a build
      run: echo flutter build web
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '3.19.1'
        channel: 'stable'
    - run: flutter --version

    - name: save secrets api key
      run: echo GOOGLE_AI_STUDIO_API_KEY=${{ secrets.GOOGLE_AI_STUDIO_API_KEY }} > .env

    - name: Run a flutter build and deploy
      run: |
        flutter pub get
        flutter build web --base-href /${{ steps.version.outputs.repository }}

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build/web
